@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_LEFT_RIGHT()

title Bounded Context Map para SRVCE

Person(public, "População", "Cidadãos em suas casas.")
Person(ace, "Agente de Controle de Endemias", "Agente da prefeitura que realiza visitas domiciliares.")
Rel(ace, public, "Faz visitas domiciliares")

System_Boundary(srvce, "Aplicacao SRVCE"){
    Container(aa, "Aplicativo Android", "Kotlin", "Fornece as funcionalidades de Registro de atendimento e disponibilização das rotas.")

    Container(api, "API", "Java e SpringBoot", "Fornece e suporta as funcionalidades da aplicação móvel, sendo a principal interface para a entrada e saída de dados.")
    
    Container(db, "SGDB", "MongoDB", "Armazena os dados recebidos, e fornece os dados existentes por meio de consulta")

    Rel(aa, api, "Envia dados", "JSON")
    Rel(api, aa, "Recebe dados", "JSON")
    Rel(api, db, "Grava", "JDBC")
    Rel(db, api, "Consulta", "JDBC")

}
System_Ext(sus, "Data SUS", "Recebe e armazena os dados.")

Rel(ace, aa, "Registra atendimentos ao publico")
Rel(aa,ace , "Recebe trajetos do dia")

Rel(api, sus, "Envia reports semanais", "JSON")

@enduml
