@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_LEFT_RIGHT()

Person(public, "População", "Cidadãos em suas casas.")
Person(ace, "Agente de Controle de Endemias", "Agente da prefeitura que realiza visitas domiciliares.")
Rel(ace, public, "Faz visitas domiciliares")

System_Boundary(srvce, "Aplicacao SRVCE"){
    Container(cli, "App Cliente","Android - Kotlin")
    Container(srv, "App Servidor","Java - Spring")
    Rel(srv, cli, "Troca infromações")
    Rel(cli, srv, "")
}
System_Ext(sus, "Data SUS", "Sistema que armazena dados de saude de todos as cidades e estados do país")

Rel(ace, cli, "Registra atendimentos ao publico")
Rel(cli,ace , "Recebe trajetos do dia")
Rel(srv, sus, "Envia reports semanais")

@enduml